apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --controller deployment -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: db-postgres
  name: db-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --controller deployment -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: db-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: probando
            - name: POSTGRES_PASSWORD
              value: probando
            - name: POSTGRES_USER
              value: postgres
            - name: TZ
              value: America/Guayaquil
          image: postgres:latest
          name: postgres-db-new
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
