apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --controller deployment -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: netdata
  name: netdata
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: netdata
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --controller deployment -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: netdata
    spec:
      containers:
        - image: netdata/netdata:latest
          name: netdata
          ports:
            - containerPort: 19999
              protocol: TCP
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
      restartPolicy: Always
