apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --controller deployment -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --controller deployment -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: web
    spec:
      containers:
        - args:
            - sh
            - -c
            - python manage.py migrate && python manage.py shell < create_superuser.py && python manage.py runserver 0.0.0.0:8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: backend_django.settings
            - name: DJANGO_SUPERUSER_EMAIL
              value: admin@example.com
            - name: DJANGO_SUPERUSER_PASSWORD
              value: admin123
            - name: DJANGO_SUPERUSER_USERNAME
              value: admin
            - name: POSTGRES_DB
              value: probando
            - name: POSTGRES_HOST
              value: db-postgres
            - name: POSTGRES_PASSWORD
              value: probando
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: postgres
          image: juanja/web123
          name: django-backend
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
